import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="flex flex-col items-center min-h-screen py-2 justify-center ">
      <Head>
        <title>PAPA Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Lets build airbnb</h1>
    </div>
  );
}
