import Head from 'next/head';
import { Banner, Header } from '../components';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>PAPA Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
    </div>
  );
}
